# EVN

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [2]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

array([[-0.4,  0.7, -0.8,  0.5],
       [ 0.5,  0.9,  0.4, -0.8],
       [ 0.4,  0.1, -0.2, -0.8],
       [ 0.1,  0.6, -0.2, -0.6],
       [ 0.7, -0.9, -0.5,  0.7]])

## element wise sum

In [3]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

(array([[-0.2,  0.1,  0. , -0.4],
        [ 0.8,  0.9, -0.5, -0.9],
        [-0.1, -0.7,  0. , -0.3],
        [ 0.7,  0.5, -0.8, -0.5],
        [ 0. ,  0.5, -0.5,  0.3]]), array([[-0.6,  0.8, -0.8,  0.1],
        [ 1.3,  1.8, -0.1, -1.7],
        [ 0.3, -0.6, -0.2, -1.1],
        [ 0.8,  1.1, -1. , -1.1],
        [ 0.7, -0.4, -1. ,  1. ]]))

In [4]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

(array([[-0.8, -0.8, -0.3,  0.5]]), array([[-1.2, -0.1, -1.1,  1. ],
        [-0.3,  0.1,  0.1, -0.3],
        [-0.4, -0.7, -0.5, -0.3],
        [-0.7, -0.2, -0.5, -0.1],
        [-0.1, -1.7, -0.8,  1.2]]))

In [5]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

(array([[ 0.1],
        [ 0.8],
        [-0.2],
        [ 0.4],
        [-0.5]]), array([[-0.3,  0.8, -0.7,  0.6],
        [ 1.3,  1.7,  1.2,  0. ],
        [ 0.2, -0.1, -0.4, -1. ],
        [ 0.5,  1. ,  0.2, -0.2],
        [ 0.2, -1.4, -1. ,  0.2]]))

In [6]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

(array([[0.7]]), array([[ 0.3,  1.4, -0.1,  1.2],
        [ 1.2,  1.6,  1.1, -0.1],
        [ 1.1,  0.8,  0.5, -0.1],
        [ 0.8,  1.3,  0.5,  0.1],
        [ 1.4, -0.2,  0.2,  1.4]]))

In [7]:
hidden + 1

array([[0.6, 1.7, 0.2, 1.5],
       [1.5, 1.9, 1.4, 0.2],
       [1.4, 1.1, 0.8, 0.2],
       [1.1, 1.6, 0.8, 0.4],
       [1.7, 0.1, 0.5, 1.7]])

In [8]:
1 + hidden

array([[0.6, 1.7, 0.2, 1.5],
       [1.5, 1.9, 1.4, 0.2],
       [1.4, 1.1, 0.8, 0.2],
       [1.1, 1.6, 0.8, 0.4],
       [1.7, 0.1, 0.5, 1.7]])

## element wise multiplication

In [9]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

(array([[-0.8, -0.3, -0.7, -0.8],
        [ 0.6, -0.9, -0.7, -0.4],
        [-0.4, -0.4,  0. ,  0.2],
        [ 0.3, -0.7, -0.9,  0.4],
        [ 0.2,  0.7, -0.7,  0.9]]), array([[ 0.32, -0.21,  0.56, -0.4 ],
        [ 0.3 , -0.81, -0.28,  0.32],
        [-0.16, -0.04, -0.  , -0.16],
        [ 0.03, -0.42,  0.18, -0.24],
        [ 0.14, -0.63,  0.35,  0.63]]))

In [10]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

(array([[-0.7, -0.8,  0.1,  0.6]]), array([[ 0.28, -0.56, -0.08,  0.3 ],
        [-0.35, -0.72,  0.04, -0.48],
        [-0.28, -0.08, -0.02, -0.48],
        [-0.07, -0.48, -0.02, -0.36],
        [-0.49,  0.72, -0.05,  0.42]]))

In [11]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

(array([[ 0. ],
        [ 0.1],
        [-0.8],
        [-0.6],
        [-0.3]]), array([[-0.  ,  0.  , -0.  ,  0.  ],
        [ 0.05,  0.09,  0.04, -0.08],
        [-0.32, -0.08,  0.16,  0.64],
        [-0.06, -0.36,  0.12,  0.36],
        [-0.21,  0.27,  0.15, -0.21]]))

In [12]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[0.9]]), array([[-0.36,  0.63, -0.72,  0.45],
        [ 0.45,  0.81,  0.36, -0.72],
        [ 0.36,  0.09, -0.18, -0.72],
        [ 0.09,  0.54, -0.18, -0.54],
        [ 0.63, -0.81, -0.45,  0.63]]))

In [13]:
hidden * 2

array([[-0.8,  1.4, -1.6,  1. ],
       [ 1. ,  1.8,  0.8, -1.6],
       [ 0.8,  0.2, -0.4, -1.6],
       [ 0.2,  1.2, -0.4, -1.2],
       [ 1.4, -1.8, -1. ,  1.4]])

In [14]:
2 * hidden

array([[-0.8,  1.4, -1.6,  1. ],
       [ 1. ,  1.8,  0.8, -1.6],
       [ 0.8,  0.2, -0.4, -1.6],
       [ 0.2,  1.2, -0.4, -1.2],
       [ 1.4, -1.8, -1. ,  1.4]])

## matrix multiplication

In [15]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[ 0. , -0.2, -0.7, -0.6,  0. ],
        [-0.4, -0.8, -0.4, -0.6,  0. ],
        [-0.2,  0.9,  0.4,  0.2, -0.5],
        [ 0.1,  0.1,  0.5, -0.4,  0.7]]),
 array([[-0.07, -1.15, -0.07, -0.54,  0.75],
        [-0.52, -0.54, -0.95, -0.44, -0.76],
        [-0.08, -0.42, -0.8 , -0.02, -0.46],
        [-0.26, -0.74, -0.69, -0.22, -0.32],
        [ 0.53,  0.2 ,  0.02, -0.26,  0.74]]))

In [16]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[-0.07, -1.15, -0.07, -0.54,  0.75],
       [-0.52, -0.54, -0.95, -0.44, -0.76],
       [-0.08, -0.42, -0.8 , -0.02, -0.46],
       [-0.26, -0.74, -0.69, -0.22, -0.32],
       [ 0.53,  0.2 ,  0.02, -0.26,  0.74]])